# Generated by Django 4.2.5 on 2023-10-24 06:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_rte_user_student_user_teacher_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RTE",
        ),
    ]
