# Generated by Django 4.2.6 on 2023-10-27 04:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_user_use_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="use_image",
            field=models.ImageField(default="Users\\default.jpg", upload_to="Users"),
        ),
    ]
