# Generated by Django 4.2.6 on 2023-10-27 04:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_alter_user_use_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="use_image",
            new_name="user_image",
        ),
    ]
