# Generated by Django 4.2.6 on 2023-10-27 04:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_rename_use_image_user_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_image",
            field=models.ImageField(default="default.jpg", upload_to="Users"),
        ),
    ]
