# Generated by Django 4.2.6 on 2023-10-27 04:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_alter_user_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_image",
            field=models.ImageField(default="USere/default.jpg", upload_to="Users"),
        ),
    ]
