# Generated by Django 4.2.6 on 2023-10-27 05:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_alter_user_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_image",
            field=models.ImageField(upload_to="Users"),
        ),
    ]
