# Generated by Django 4.2.6 on 2023-10-29 04:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_course_section_student_sections"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="sections",
        ),
        migrations.DeleteModel(
            name="Section",
        ),
    ]
