# Generated by Django 4.2.6 on 2023-10-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_remove_student_sections_delete_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="semester",
            field=models.CharField(
                choices=[("first", "First"), ("econd", "Second")],
                default="first",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="year",
            field=models.CharField(
                choices=[("first", "First"), ("second", "Second"), ("third", "Third")],
                default="first",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="courses",
            field=models.ManyToManyField(related_name="students", to="api.course"),
        ),
        migrations.AddField(
            model_name="student",
            name="fieldofstudy",
            field=models.CharField(
                choices=[
                    ("computing", "Computing"),
                    ("networking", "Networking"),
                    ("multimedia", "Multimedia"),
                ],
                default="computing",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="section",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="student",
            name="semester",
            field=models.CharField(
                choices=[("first", "First"), ("econd", "Second")],
                default="first",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="year",
            field=models.CharField(
                choices=[("first", "First"), ("second", "Second"), ("third", "Third")],
                default="first",
                max_length=20,
            ),
        ),
    ]
