# Generated by Django 4.2.6 on 2023-10-29 04:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_course_semester_course_year_student_courses_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="fieldofstudy",
            field=models.CharField(
                choices=[
                    ("computing", "Computing"),
                    ("networking", "Networking"),
                    ("multimedia", "Multimedia"),
                ],
                default="computing",
                max_length=20,
            ),
        ),
    ]
