# Generated by Django 4.2.7 on 2024-01-19 05:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0018_hall_seat"),
    ]

    operations = [
        migrations.AddField(
            model_name="hall",
            name="seats",
            field=models.IntegerField(default=6),
        ),
    ]
