# Generated by Django 4.2.7 on 2024-01-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0019_hall_seats"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hall",
            old_name="seats",
            new_name="noOfSeats",
        ),
        migrations.RemoveField(
            model_name="seat",
            name="hall",
        ),
        migrations.AddField(
            model_name="seat",
            name="hall",
            field=models.ManyToManyField(related_name="seat", to="api.hall"),
        ),
    ]
