# Generated by Django 4.2.7 on 2024-01-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0023_alter_seat_hall"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seat",
            name="hall",
        ),
        migrations.AddField(
            model_name="seat",
            name="hall",
            field=models.ManyToManyField(related_name="seat", to="api.hall"),
        ),
    ]
