# Generated by Django 4.2.7 on 2024-01-19 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0024_remove_seat_hall_seat_hall"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seat",
            name="hall",
        ),
        migrations.AddField(
            model_name="seat",
            name="hall",
            field=models.ForeignKey(
                default=6,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seats",
                to="api.hall",
            ),
        ),
    ]
