# Generated by Django 4.2.7 on 2024-01-20 05:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0026_alter_hall_noofseats"),
    ]

    operations = [
        migrations.AddField(
            model_name="seat",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
