# Generated by Django 4.2.7 on 2024-01-28 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0027_seat_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seat",
            name="hall",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seats",
                to="api.hall",
            ),
        ),
        migrations.CreateModel(
            name="HallSpaces",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("columnAfter", models.IntegerField(blank=True)),
                (
                    "hall",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spaces",
                        to="api.hall",
                    ),
                ),
            ],
        ),
    ]
