# Generated by Django 4.2.7 on 2024-01-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0028_alter_seat_hall_hallspaces"),
    ]

    operations = [
        migrations.AddField(
            model_name="hallspaces",
            name="is_space",
            field=models.BooleanField(default=False),
        ),
    ]
