# Generated by Django 4.2.7 on 2024-02-02 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0029_hallspaces_is_space"),
    ]

    operations = [
        migrations.CreateModel(
            name="HallColumnSpaces",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("columnAfter", models.IntegerField(blank=True)),
                ("is_space", models.BooleanField(default=False)),
                (
                    "hall",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="columnspaces",
                        to="api.hall",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HallRowSpaces",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rowAfter", models.IntegerField(blank=True)),
                ("is_space", models.BooleanField(default=False)),
                (
                    "hall",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rowspaces",
                        to="api.hall",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="HallSpaces",
        ),
    ]
