# Generated by Django 4.2.7 on 2024-02-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0031_event_eventcourses"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
