# Generated by Django 4.2.7 on 2024-02-10 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0034_allocation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allocation",
            name="seat",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allocationseat",
                to="api.seat",
            ),
        ),
    ]
